const mainContentActionTypes = {
    ACTIVATE_SIDEBAR:'ACTIVATE_SIDEBAR',
    ACTIVATE_SPECIFIC_STOCK:'ACTIVATE_SPECIFIC_STOCK',
    ACTIVATE_STOCK_EDIT:'ACTIVATE_STOCK_EDIT',
    ACTIVATE_STOCK_ADD:'ACTIVATE_STOCK_ADD',

}

export default mainContentActionTypes