const portfolioActionTypes ={
    FETCH_PORTFOLIO_START:'FETCH_PORTFOLIO_START',
    FETCH_PORTFOLIO_SUCCESS:'FETCH_PORTFOLIO_SUCCESS',
    FETCH_PORTFOLIO_FAILURE:'FETCH_PORTFOLIO_FAILURE',
    FETCH_PORTFOLIO:'FETCH_PORTFOLIO',
    EDIT_STOCK:'EDIT_STOCK',
    REMOVE_STOCK_POSITION:'REMOVE_STOCK_POSITION',
    REMOVE_STOCK_COMPLETELY:'REMOVE_STOCK_COMPLETELY',
    ADD_STOCK:'ADD_STOCK',
    TOGGLE_PORTFOLIO:'TOGGLE_PORTFOLIO',
    TOGGLE_ADD_TO_PORTFOLIO:'TOGGLE_ADD_TO_PORTFOLIO',

}

export default portfolioActionTypes